"""Transcript document export (ensemble mode): .txt and/or .docx.

Turns the consensus word stream into a readable transcript document:
words -> sentences (terminal punctuation) -> paragraphs (speech pauses),
optionally prefixed with ``[HH:MM:SS]`` paragraph timestamps -- the
layout professional transcription services deliver.

In .docx output, words whose ensemble agreement fell below the
confidence threshold are highlighted yellow so a human reviewer can jump
straight to the uncertain spots. Requires ``pip install python-docx``
(the .txt path has no extra dependency).
"""
from __future__ import annotations

import datetime as _dt
from typing import Dict, List, Optional

from .utils import has_terminal_punctuation

PAUSE_PARAGRAPH_SECONDS = 1.75   # silence gap that starts a new paragraph
MAX_SENTENCE_WORDS = 60          # hard stop for run-on unpunctuated speech
MAX_PARAGRAPH_SENTENCES = 8
LOW_CONF_THRESHOLD = 0.5


def _fmt_ts(seconds: Optional[float]) -> str:
    if seconds is None:
        return "[--:--:--]"
    s = int(seconds)
    return f"[{s // 3600:02d}:{(s % 3600) // 60:02d}:{s % 60:02d}]"


def group_into_sentences(consensus: List[Dict]) -> List[Dict]:
    sentences: List[Dict] = []
    current: List[Dict] = []
    for w in consensus:
        current.append(w)
        if has_terminal_punctuation(w["word"]) or len(current) >= MAX_SENTENCE_WORDS:
            sentences.append(_close_sentence(current))
            current = []
    if current:
        sentences.append(_close_sentence(current))
    return sentences


def _close_sentence(words: List[Dict]) -> Dict:
    starts = [w["start"] for w in words if w.get("start") is not None]
    ends = [w["end"] for w in words if w.get("end") is not None]
    return {
        "words": words,
        "text": " ".join(w["word"] for w in words),
        "start": min(starts) if starts else None,
        "end": max(ends) if ends else None,
    }


def group_into_paragraphs(sentences: List[Dict]) -> List[List[Dict]]:
    paragraphs: List[List[Dict]] = []
    current: List[Dict] = []
    prev_end: Optional[float] = None
    for sent in sentences:
        gap = (sent["start"] - prev_end
               if sent["start"] is not None and prev_end is not None else 0.0)
        if current and (gap > PAUSE_PARAGRAPH_SECONDS
                        or len(current) >= MAX_PARAGRAPH_SENTENCES):
            paragraphs.append(current)
            current = []
        current.append(sent)
        if sent["end"] is not None:
            prev_end = sent["end"]
    if current:
        paragraphs.append(current)
    return paragraphs


def write_txt(path: str, paragraphs: List[List[Dict]],
              timestamps: bool = True) -> None:
    lines: List[str] = []
    for para in paragraphs:
        text = " ".join(s["text"] for s in para)
        if timestamps:
            first_ts = next((s["start"] for s in para
                             if s["start"] is not None), None)
            lines.append(f"{_fmt_ts(first_ts)} {text}")
        else:
            lines.append(text)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n\n".join(lines) + "\n")


def write_docx(path: str, paragraphs: List[List[Dict]], media_name: str,
               timestamps: bool = True,
               low_conf: float = LOW_CONF_THRESHOLD) -> bool:
    """Write a .docx transcript. Returns False if python-docx is missing."""
    try:
        import docx
        from docx.enum.text import WD_COLOR_INDEX
    except ImportError:
        print("[warn] python-docx not installed -- skipping .docx export "
              "(pip install python-docx).")
        return False

    doc = docx.Document()
    doc.add_heading(f"Transcript — {media_name}", level=1)
    meta = doc.add_paragraph()
    meta_run = meta.add_run(
        f"Generated by word-align on {_dt.date.today().isoformat()} · "
        "ensemble consensus transcription · "
        "highlighted words fell below the agreement threshold and should "
        "be reviewed against the audio.")
    meta_run.italic = True

    for para in paragraphs:
        p = doc.add_paragraph()
        if timestamps:
            first_ts = next((s["start"] for s in para
                             if s["start"] is not None), None)
            ts_run = p.add_run(_fmt_ts(first_ts) + " ")
            ts_run.bold = True
        buffer: List[str] = []
        for sent in para:
            for w in sent["words"]:
                if float(w.get("conf", 1.0)) < low_conf:
                    if buffer:
                        p.add_run(" ".join(buffer) + " ")
                        buffer = []
                    hl = p.add_run(w["word"])
                    hl.font.highlight_color = WD_COLOR_INDEX.YELLOW
                    p.add_run(" ")
                else:
                    buffer.append(w["word"])
        if buffer:
            p.add_run(" ".join(buffer))
    doc.save(path)
    return True


def export_transcript(base: str, media_name: str, consensus: List[Dict],
                      doc_format: str = "txt",
                      timestamps: bool = True) -> None:
    """Write the consensus transcript in the requested format(s)."""
    if doc_format == "none":
        return
    paragraphs = group_into_paragraphs(group_into_sentences(consensus))
    low = sum(1 for w in consensus
              if float(w.get("conf", 1.0)) < LOW_CONF_THRESHOLD)
    if doc_format in ("txt", "both"):
        write_txt(f"{base}_transcript.txt", paragraphs, timestamps)
        print(f"[ok] Transcript .txt written ({len(paragraphs)} paragraphs)")
    if doc_format in ("docx", "both"):
        ok = write_docx(f"{base}_transcript.docx", paragraphs, media_name,
                        timestamps)
        if ok:
            print(f"[ok] Transcript .docx written ({len(paragraphs)} "
                  f"paragraphs, {low} words highlighted for review)")
        elif doc_format == "docx":
            write_txt(f"{base}_transcript.txt", paragraphs, timestamps)
            print("[ok] Fell back to .txt transcript")
    if low:
        print(f"[info] {low} low-agreement words flagged for review")
